### PR TITLE
Persist etcd data

### LINKED ISSUE #42: etcd data not persisted
etcd data is not persisted, as a result all the cluster config is lost as soon as Docker is restarted. This is an issue when the user wants to reconfigure the Docker daemon.

### PR DESCRIPTION
**Pull request by antoineco**
Fixes #42

### CODE REVIEW

**Comment by sebgoa** [comment]
Great, thanks @antoineco I am merging and will build a new release in coming weeks.
I am working on a new driver.

**Comment by sebgoa** [comment]
@antoineco ah mais tu es breton 👍

**Comment by antoineco** [comment]
Tout à fait, cela fait sûrement de nous des cousins :D

Thanks for merging this! This will allow devs to restart their vm without losing the cluster state.
Great project by the way 👍

**Comment by sebgoa** [comment]
thanks. Feel free to tell your friends about it :)

**Pull request merged**
